const types = {
  SHOW_LIST_TASKS_SUCCESS: "SHOW_LIST_TASKS_SUCCESS",
  SHOW_LIST_TASKS_FAILURE: "SHOW_LIST_TASKS_FAILURE",
  SHOW_LIST_TASKS_STARTED: "SHOW_LIST_TASKS_STARTED",
};

export default types;
